### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Cluster)
add_subdirectory(ClusterContent)
add_subdirectory(Generated)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Clusterplugin
    ClusterContentplugin
    Generated_Bundles_Materialsplugin
    Generated_QtQuick3D_GenericCarModelplugin
    Generated_QtQuick3D_Lightsplugin)