### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Generated)
add_subdirectory(GLOContent)
add_subdirectory(GLO)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	Generated_QtQuick3D_GenericCarModelplugin
	Generated_QtQuick3D_Lightsplugin
	GLOContentplugin
	GLOplugin)