### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Generated)
add_subdirectory(VehicleData)
add_subdirectory(GLOContent)
add_subdirectory(GLO)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Generated_QtQuick3D_GenericCarModelplugin
    Generated_QtQuick3D_Lightsplugin
    VehicleDataplugin
    GLOContentplugin
    GLOplugin)