/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change
*/

#include <QtQml/qqmlextensionplugin.h>

Q_IMPORT_QML_PLUGIN(MainPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_GenericCarModelPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_LightsPlugin)
Q_IMPORT_QML_PLUGIN(contentPlugin)
Q_IMPORT_QML_PLUGIN(DataPlugin)
Q_IMPORT_QML_PLUGIN(IVIPlugin)
