version: 0.2

phases:
  pre_build:
    commands:
      - echo "=== ECR Qt Container Test ==="
      - echo "Build started on $(date)"
      - echo "Testing Qt installation..."
      - ls -la /opt/Qt/6.8.3/
      - echo ""
      - echo "Checking Boot2Qt components:"
      - ls -la /opt/Qt/6.8.3/Boot2Qt/
      - find /opt/Qt/6.8.3/Boot2Qt -name "environment-setup-*" | head -3
      
  build:
    commands:
      - echo "=== Testing Desktop Qt Build ==="
      - cd test-qt-build
      - mkdir -p build-desktop && cd build-desktop
      - cmake -DCMAKE_BUILD_TYPE=Release ..
      - cmake --build .
      - echo "Desktop Qt build result:"
      - ls -la QtHelloWorld || echo "Desktop build failed"
      - ./QtHelloWorld || echo "Desktop execution failed"
      - cd ..
      
      - echo ""
      - echo "=== Testing Boot2Qt Cross-Compilation ==="
      - echo "Setting up Boot2Qt environment..."
      - echo "Fixing hardcoded paths in toolchain..."
      - sed -i 's|/usr/local/oe-sdk-hardcoded-buildpath/sysroots|/opt/Qt/6.8.3/Boot2Qt/aws-ec2-arm64/toolchain/sysroots|g' /opt/Qt/6.8.3/Boot2Qt/aws-ec2-arm64/toolchain/environment-setup-armv8-2a-poky-linux
      - sed -i 's|/usr/local/oe-sdk-hardcoded-buildpath/sysroots|/opt/Qt/6.8.3/Boot2Qt/aws-ec2-arm64/toolchain/sysroots|g' /opt/Qt/6.8.3/Boot2Qt/aws-ec2-arm64/toolchain/sysroots/x86_64-pokysdk-linux/usr/share/cmake/OEToolchainConfig.cmake
      - find /opt/Qt/6.8.3/Boot2Qt/aws-ec2-arm64/toolchain -type f \( -name "*.cmake" -o -name "*.pc" -o -name "*.la" -o -name "*.conf" -o -name "*.prf" \) -exec sed -i 's|/usr/local/oe-sdk-hardcoded-buildpath/sysroots|/opt/Qt/6.8.3/Boot2Qt/aws-ec2-arm64/toolchain/sysroots|g' {} \; 2>/dev/null || true
      - . /opt/Qt/6.8.3/Boot2Qt/aws-ec2-arm64/toolchain/environment-setup-armv8-2a-poky-linux
      - export OECORE_CMAKE_TOOLCHAIN_FILE="/opt/Qt/6.8.3/Boot2Qt/aws-ec2-arm64/toolchain/sysroots/x86_64-pokysdk-linux/usr/share/cmake/OEToolchainConfig.cmake"
      - echo "Cross-compiler:" "$CC"
      - echo "Target arch:" "$OECORE_TARGET_ARCH"
      - echo "Sysroot:" "$OECORE_TARGET_SYSROOT"
      - echo "CMake toolchain:" "$OECORE_CMAKE_TOOLCHAIN_FILE"
      - echo "Looking for libgcc files:"
      - find /opt/Qt/6.8.3/Boot2Qt -name "*libgcc*" | head -5
      - echo "Checking compiler version:"
      - $CC --version | head -2
      
      - rm -rf build-boot2qt
      - mkdir -p build-boot2qt && cd build-boot2qt
      - |
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE="$OECORE_CMAKE_TOOLCHAIN_FILE" \
          -DQt6_DIR="$OECORE_TARGET_SYSROOT/usr/lib/cmake/Qt6" \
          -DQT_HOST_PATH=/opt/Qt/6.8.3/gcc_64 || echo "Boot2Qt cmake failed"
      - cmake --build . || echo "Boot2Qt build failed"
      - echo "Boot2Qt build result:"
      - ls -la QtHelloWorld || echo "Boot2Qt binary not found"
      - file QtHelloWorld 2>/dev/null || echo "Cannot check Boot2Qt binary"
      
  post_build:
    commands:
      - echo "=== Test Summary ==="
      - echo "Build completed on $(date)"
      - cd $CODEBUILD_SRC_DIR/test-qt-build
      - pwd
      - ls -la
      - |
        if [ -f build-desktop/QtHelloWorld ]; then
          echo "Desktop Qt: SUCCESS"
        else
          echo "Desktop Qt: FAILED"
        fi
      - |
        if [ -f build-boot2qt/QtHelloWorld ]; then
          echo "Boot2Qt: SUCCESS"
        else
          echo "Boot2Qt: FAILED"
        fi

