/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change.
*/
#ifndef APP_ENVIRONMENT_H
#define APP_ENVIRONMENT_H

#include <QGuiApplication>
#include "qqmlextensionplugin.h"

Q_IMPORT_QML_PLUGIN(ClusterContentPlugin)
Q_IMPORT_QML_PLUGIN(Generated_QtQuick3D_GenericCarModelPlugin)
Q_IMPORT_QML_PLUGIN(Generated_QtQuick3D_LightsPlugin)
Q_IMPORT_QML_PLUGIN(Generated_Bundles_MaterialsPlugin)
Q_IMPORT_QML_PLUGIN(ClusterPlugin)
Q_IMPORT_QML_PLUGIN(VehicleDataPlugin)

const char mainQmlFile[] = "qrc:/qt/qml/ClusterContent/App.qml";

#ifdef BUILD_QDS_COMPONENTS

Q_IMPORT_QML_PLUGIN(QtQuick_Studio_ComponentsPlugin)
Q_IMPORT_QML_PLUGIN(QtQuick_Studio_EffectsPlugin)
Q_IMPORT_QML_PLUGIN(QtQuick_Studio_ApplicationPlugin)
Q_IMPORT_QML_PLUGIN(FlowViewPlugin)
Q_IMPORT_QML_PLUGIN(QtQuick_Studio_LogicHelperPlugin)
Q_IMPORT_QML_PLUGIN(QtQuick_Studio_MultiTextPlugin)
Q_IMPORT_QML_PLUGIN(QtQuick_Studio_EventSimulatorPlugin)
Q_IMPORT_QML_PLUGIN(QtQuick_Studio_EventSystemPlugin)

#endif

inline void set_qt_environment() {
    qputenv("QML_COMPAT_RESOLVE_URLS_ON_ASSIGNMENT", "1");
    qputenv("QT_AUTO_SCREEN_SCALE_FACTOR", "1");
    qputenv("QT_ENABLE_HIGHDPI_SCALING", "0");
    qputenv("QT_LOGGING_RULES", "qt.qml.connections=false");
    qputenv("QT_QUICK_CONTROLS_CONF", ":/qtquickcontrols2.conf");
}

#endif // APP_ENVIRONMENT_H
