name: Boot to Qt Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: codebuild-antares-cluster-boot2qt-docker-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Boot to Qt build
        run: |
          chmod +x .github/workflows/build-boot2qt.sh
          .github/workflows/build-boot2qt.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: boot2qt-build-${{ github.run_number }}
          path: artifacts/aws/