name: Build Antares Qt Project for Linux

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # In case you have submodules
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libgl1-mesa-dev \
          libxkbcommon-dev \
          libxcb-xkb-dev
          
    - name: Install Qt for Linux
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.8.3
        host: linux
        target: desktop
        arch: linux_gcc_64
        modules: qtwebsockets qtquick3d qtshadertools qtquicktimeline qt5compat qtshadertools qtwebsockets qtmultimedia qtserialbus qtserialport
        cache: true
        
    - name: Build Qt Designer Components
      run: |
        # Clone and build Qt Designer Components as specified in README
        git clone https://code.qt.io/qt-labs/qtquickdesigner-components.git
        mkdir buildDScomponents
        cd buildDScomponents
        cmake -GNinja \
          -DCMAKE_INSTALL_PREFIX=$Qt6_DIR \
          -DCMAKE_BUILD_TYPE=Release \
          ../qtquickdesigner-components
        cmake --build .
        cmake --install .
        
    - name: Build Common Library
      run: |
        cd common
        mkdir build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DQt6_DIR=$Qt6_DIR
        cmake --build .
        
    - name: Build Cluster Application
      run: |
        cd Cluster
        mkdir build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DQt6_DIR=$Qt6_DIR
        cmake --build .
        
    - name: Build IVI Application
      run: |
        cd IVI
        mkdir build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DQt6_DIR=$Qt6_DIR
        cmake --build .
        
    - name: Package Linux binaries
      run: |
        # Create a directory for artifacts
        mkdir -p artifacts
        
        # Copy built applications
        if [ -f "Cluster/build/cluster" ]; then
          cp Cluster/build/cluster artifacts/
        fi
        
        if [ -f "IVI/build/ivi" ]; then
          cp IVI/build/ivi artifacts/
        fi
        
        # Copy any shared libraries if needed
        if [ -f "common/build/libcommon.so" ]; then
          cp common/build/libcommon.so artifacts/
        fi
        
        # Create a simple info file
        echo "Linux build completed on $(date)" > artifacts/build_info.txt
        echo "Qt version: 6.8.3" >> artifacts/build_info.txt
        echo "Platform: Ubuntu Linux" >> artifacts/build_info.txt
        echo "Architecture: x86_64" >> artifacts/build_info.txt
        
    - name: Upload Linux binaries
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: antares-linux-binaries-${{ github.sha }}
        path: artifacts/
        retention-days: 30
        
    - name: Upload logs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: linux-build-logs-${{ github.sha }}
        path: |
          */build/CMakeFiles/CMakeOutput.log
          */build/CMakeFiles/CMakeError.log
        retention-days: 7
